### ISSUE TITLE
Many undefined index vars

### ISSUE THREAD

**Issue by yourchoice** [lvu/rtf2html#3]
In windows cmd 

> rtf2htm sample.rtf sample.html

...
Notice: Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159
PHP Notice:  Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159

Notice: Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159
PHP Notice:  Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133

Notice: Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133
PHP Notice:  Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133

Notice: Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133
PHP Notice:  Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159

Notice: Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159
PHP Notice:  Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159

Notice: Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159
PHP Notice:  Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133

Notice: Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133
PHP Notice:  Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133

Notice: Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133
PHP Notice:  Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159

Notice: Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159
PHP Notice:  Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159

Notice: Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159
PHP Notice:  Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 60

Notice: Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 60
PHP Notice:  Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 80

Notice: Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 80
PHP Notice:  Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133

Notice: Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133
PHP Notice:  Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133

Notice: Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133
PHP Notice:  Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159

Notice: Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159
PHP Notice:  Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159

Notice: Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159
PHP Notice:  Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133

Notice: Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133
PHP Notice:  Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133

Notice: Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133
PHP Notice:  Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159

Notice: Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159
PHP Notice:  Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159

Notice: Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159
PHP Notice:  Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133

Notice: Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133
PHP Notice:  Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133

Notice: Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133
PHP Notice:  Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159

Notice: Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159
PHP Notice:  Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159

Notice: Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159
PHP Notice:  Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133

Notice: Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133
PHP Notice:  Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133

Notice: Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133
PHP Notice:  Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159

Notice: Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159
PHP Notice:  Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159

Notice: Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159
PHP Notice:  Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133

Notice: Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133
PHP Notice:  Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133

Notice: Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133
PHP Notice:  Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159

Notice: Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159
PHP Notice:  Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159

Notice: Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159
PHP Notice:  Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133

Notice: Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133
PHP Notice:  Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133

Notice: Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133
PHP Notice:  Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159

Notice: Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159
PHP Notice:  Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159

Notice: Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159
PHP Notice:  Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133

Notice: Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133
PHP Notice:  Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133

Notice: Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133
PHP Notice:  Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159

Notice: Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159
PHP Notice:  Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159

Notice: Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159
PHP Notice:  Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133

Notice: Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133
PHP Notice:  Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133

Notice: Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133
PHP Notice:  Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159

Notice: Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159
PHP Notice:  Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159

Notice: Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159
PHP Notice:  Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133

Notice: Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133
PHP Notice:  Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133

Notice: Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133
PHP Notice:  Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159

Notice: Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159
PHP Notice:  Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159

Notice: Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159
PHP Notice:  Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133

Notice: Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133
PHP Notice:  Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133

Notice: Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133
PHP Notice:  Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159

Notice: Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159
PHP Notice:  Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159

Notice: Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159
PHP Notice:  Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133

Notice: Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133
PHP Notice:  Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133

Notice: Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133
PHP Notice:  Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159

Notice: Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159
PHP Notice:  Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159

Notice: Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159
PHP Notice:  Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133

Notice: Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133
PHP Notice:  Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133

Notice: Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133
PHP Notice:  Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159

Notice: Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159
PHP Notice:  Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159

Notice: Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159
PHP Notice:  Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133

Notice: Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133
PHP Notice:  Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133

Notice: Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133
PHP Notice:  Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159

Notice: Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159
PHP Notice:  Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159

Notice: Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159
PHP Notice:  Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133

Notice: Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133
PHP Notice:  Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133

Notice: Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133
PHP Notice:  Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159

Notice: Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159
PHP Notice:  Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159

Notice: Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159
PHP Notice:  Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133

Notice: Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133
PHP Notice:  Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133

Notice: Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133
PHP Notice:  Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159

Notice: Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159
PHP Notice:  Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159

Notice: Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159
PHP Notice:  Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133

Notice: Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133
PHP Notice:  Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133

Notice: Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133
PHP Notice:  Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159

Notice: Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159
PHP Notice:  Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159

Notice: Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159
PHP Notice:  Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133

Notice: Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133
PHP Notice:  Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133

Notice: Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133
PHP Notice:  Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159

Notice: Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159
PHP Notice:  Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159

Notice: Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159
PHP Notice:  Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 60

Notice: Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 60
PHP Notice:  Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 80

Notice: Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 80
PHP Notice:  Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133

Notice: Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133
PHP Notice:  Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133

Notice: Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133
PHP Notice:  Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159

Notice: Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159
PHP Notice:  Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159

Notice: Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159
PHP Notice:  Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133

Notice: Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133
PHP Notice:  Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133

Notice: Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133
PHP Notice:  Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159

Notice: Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159
PHP Notice:  Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159

Notice: Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159
PHP Notice:  Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 60

Notice: Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 60
PHP Notice:  Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 80

Notice: Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 80
PHP Notice:  Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133

Notice: Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133
PHP Notice:  Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133

Notice: Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133
PHP Notice:  Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159

Notice: Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159
PHP Notice:  Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159

Notice: Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159
PHP Notice:  Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133

Notice: Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133
PHP Notice:  Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133

Notice: Undefined index: FOOTNOTE in E:...\rtf2htm\htmlparser.php on line 133
PHP Notice:  Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159

Notice: Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159
PHP Notice:  Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159

Notice: Undefined index: SUP in E:...\rtf2htm\htmlparser.php on line 159

**Comment by lvu** [comment]
What is htmlparser.php? There is no such file in rtf2html.

**Comment by yourchoice** [comment]
Sorry, I think is a confusion with http://freecode.com/projects/rtf2htm/ 

Sorry my mistake
